---
- name: Create a VM from a template
  hosts: localhost
  tasks:
    - name: Clone the template
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pw }}"
        validate_certs: False
        name: "{{ vm_name }}"
        template: rhel85
        datacenter: "{{ datacenter_name }}"
        folder: /New
        state: poweredon
        cluster: "Laws Cluster"
        wait_for_ip_address: yes
