---
- name: Create a VM from a template
  hosts: localhost
  tasks:
    - name: Clone the template
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        #username: "{{ vcenter_user }}"
        #password: "{{ vcenter_pw }}"
        validate_certs: False
        name: "{{ vm_name }}"
        template: rhel89
        datacenter: "{{ datacenter_name }}"
        folder: /New
        state: poweredon
        cluster: "PHX-SPOC005-1"
        wait_for_ip_address: yes
