---
- name: Get VM details
  hosts: localhost
  collections:
    - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: "{{ ncp_ip }}"
      nutanix_username: "{{ ncp_username }}"
      nutanix_password: "{{ ncp_password }}"
      validate_certs: false
  tasks:
    - name: Get VM info
      ntnx_vms_info:
        filter:
          vm_name: "{{ vm.name }}"
        kind: vm
      register: result
